export const ACTION_TYPES = {
    ON_DELETE_CHAT : "ON_DELETE_CHAT",
    ON_EDIT_MESSAGE : "ON_EDIT_MESSAGE",
    ON_SELECT_CHAT : "ON_SELECT_CHAT",
    ON_NEW_CHAT : "ON_NEW_CHAT",
    ON_NEW_MESSAGE : "ON_NEW_MESSAGE",
    ON_DELETE_MESSAGE : "ON_DELETE_MESSAGE",
}